In [17]:
#Mean removal
import numpy as np
from sklearn import preprocessing
data = np.array([[2],[4],[6],[8],[10]])

mean = np.mean(data)
mean_removed= data-mean
print(mean_removed)
print(mean_removed.std(axis=0))
print(mean_removed.mean(axis=0))

data_standardize = preprocessing.scale(data)
print(data_standardize)
print(data_standardize.std(axis=0))
print(data_standardize.mean(axis=0))

[[-4.]
 [-2.]
 [ 0.]
 [ 2.]
 [ 4.]]
[2.82842712]
[0.]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
[1.]
[0.]


In [6]:
#Linear_regression
from sklearn.linear_model import LinearRegression
import numpy as np

years = np.array([[1],[2],[3],[4],[5]])
salary = np.array([30000,35000,40000,45000,50000])

model = LinearRegression()
model.fit(years,salary)

predicted_salary = model.predict([[6],[10]])
print(predicted_salary)

[55000. 75000.]


In [9]:
#label encoding
from sklearn import preprocessing

labels = ['Mango','Banana','Apple','Mango','Orange','Banana']
print(labels)

label_encoder = preprocessing.LabelEncoder()

op = label_encoder.fit_transform(labels)

print(op)

test_labels = ['Mango','Apple']
print(label_encoder.transform(test_labels))
test_codes = [0,1]
print(label_encoder.inverse_transform(test_codes))

['Mango', 'Banana', 'Apple', 'Mango', 'Orange', 'Banana']
[2 1 0 2 3 1]
[2 0]
['Apple' 'Banana']


In [11]:
#Binarization

import numpy as np
from sklearn import preprocessing

data = np.array([[10000],[12000],[12600],[9000],[15000]])
print(data)
print('='*50)
binarized_data = preprocessing.Binarizer(threshold=9999).transform(data)
print(binarized_data)

[[10000]
 [12000]
 [12600]
 [ 9000]
 [15000]]
[[1]
 [1]
 [1]
 [0]
 [1]]


In [12]:
#Normalization

import numpy as np
from sklearn import preprocessing

data = np.array([[3,4],[1,2],[5,12]])
print(data)
print('='*50)

#l1

normalized_l1=preprocessing.normalize(data,norm='l1')
normalized_l2=preprocessing.normalize(data,norm='l2')

print(normalized_l1)
print('='*50)
print(normalized_l2)


[[ 3  4]
 [ 1  2]
 [ 5 12]]
[[0.42857143 0.57142857]
 [0.33333333 0.66666667]
 [0.29411765 0.70588235]]
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.38461538 0.92307692]]


In [14]:
#scaling
import numpy as np
from sklearn import preprocessing
data = np.array([[10],[20],[30],[40],[50]])
print(data)
print('='*50)
data_Scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_data = data_Scaler.fit_transform(data)
print(scaled_data)

[[10]
 [20]
 [30]
 [40]
 [50]]
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
